### ISSUE TITLE
提示没有sklearn.metrics.base'模块

### ISSUE THREAD

**Issue by liudapeng2333** [Huang-3/Celeb-reID#7]
问题如下：
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from reid.evaluators_1stream import Evaluator
  File "/home/lxz/KunPeng_Liu/Celeb-reID/reid/__init__.py", line 3, in <module>
    from . import evaluation_metrics
  File "/home/lxz/KunPeng_Liu/Celeb-reID/reid/evaluation_metrics/__init__.py", line 4, in <module>
    from .ranking import cmc, mean_ap
  File "/home/lxz/KunPeng_Liu/Celeb-reID/reid/evaluation_metrics/ranking.py", line 5, in <module>
    from sklearn.metrics.base import _average_binary_score
ModuleNotFoundError: No module named 'sklearn.metrics.base'

我在网上找了好久都没有找到这个模块，但是sklearn.metrics这个模块是有的，估计是版本不对？
作者能告诉一下具体的版本吗？

**Comment by YINYIPENG-EN** [comment]
是该作者发布代码有问题，正确的应该改为：sklearn.metrics._base就可以调用了
